### ISSUE TITLE
c++11 linux

### ISSUE THREAD

**Issue by Xamis** [resfilter/eehack#8]
If at all possible, please try adding:
QMAKE_CXXFLAGS += -std=c++11
somewhere in the .pro file, so it adds it automatically to the MAKEFILE.
Thanks

**Comment by resfilter** [comment]
thanks for the feedback.

after a bit of googling, i've used CONFIG += c++11 due to qt standardization i think it's the correct choice.

QMAKE_CXXFLAGS += -std=c++11 makes windows whine a bit, but CONFIG += c++11 doesn't.

please let me know if that didnt' fix the problem for you.

i'll get a linux vm going soon so i can test all of this.

**Comment by Xamis** [comment]
Thanks!
that worked perfectly
